package br.edu.unijui.gui;

import br.edu.unijui.pcn.logic.DBManager;
import br.edu.unijui.pcn.logic.IsolationCSVImporter;
import br.edu.unijui.pcn.logic.IsolationRecord;
import br.edu.unijui.pcn.utils.XMLHandler;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import javax.swing.SwingUtilities;

/**
 * Interface implementada parcialmente pelo professor. 
 * Siga as instruções da avaliação para construir seu programa completo.
 * @author Rafael Zancan Frantz
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {        
        initComponents();    
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jpMain = new javax.swing.JPanel();
        jpDatabaseConnection = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hostName = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        jbLoadXML = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        enableTransactions = new javax.swing.JTextField();
        dbName = new javax.swing.JTextField();
        jpLoadData = new javax.swing.JPanel();
        jbInputFileButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        totalRegisters = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numberCities = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numberStates = new javax.swing.JTextField();
        jbRunSystem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectedFilesJList = new javax.swing.JList<>();
        jtfNumberThree = new javax.swing.JLabel();
        jtfNumberOne = new javax.swing.JLabel();
        jpFindIsolationIndex = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        highestIsolationIndex = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lowestIsolationIndex = new javax.swing.JTextField();
        jbFindIsolationIndex = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jcbWhereToFind = new javax.swing.JComboBox<>();
        jtfNumberTwo1 = new javax.swing.JLabel();
        jpXMLTransformer = new javax.swing.JPanel();
        xmlOutputFileName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jbExport = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();
        jtfNumberFour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("COVID-19 Isolation Index System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jpMain.setEnabled(false);

        jpDatabaseConnection.setBorder(javax.swing.BorderFactory.createTitledBorder("Database Connection Settings"));

        jLabel6.setText("Host name:");

        jLabel7.setText("Username:");

        jLabel8.setText("Password:");

        jLabel9.setText("Database name:");
        jLabel9.setDoubleBuffered(true);

        hostName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostNameActionPerformed(evt);
            }
        });

        jLabel10.setText("Port:");

        jbLoadXML.setText("Load XML Conf");
        jbLoadXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoadXMLActionPerformed(evt);
            }
        });

        jLabel12.setText("Enable Transactions:");

        javax.swing.GroupLayout jpDatabaseConnectionLayout = new javax.swing.GroupLayout(jpDatabaseConnection);
        jpDatabaseConnection.setLayout(jpDatabaseConnectionLayout);
        jpDatabaseConnectionLayout.setHorizontalGroup(
            jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                        .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(134, 134, 134))
                            .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                                .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(hostName, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(username)
                                    .addComponent(dbName, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                                .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 23, Short.MAX_VALUE))
                            .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(49, 49, 49))
                            .addComponent(enableTransactions)))
                    .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                        .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbLoadXML)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpDatabaseConnectionLayout.setVerticalGroup(
            jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                        .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(4, 4, 4)
                        .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9)
                        .addGap(28, 28, 28))
                    .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enableTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLoadXML)
                .addContainerGap())
        );

        jLabel12.getAccessibleContext().setAccessibleDescription("");

        jpLoadData.setBorder(javax.swing.BorderFactory.createTitledBorder("Load Data to Database"));

        jbInputFileButton.setText("Select the CSV files...");
        jbInputFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputFileButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Total registers uploaded:");

        totalRegisters.setEnabled(false);

        jLabel4.setText("Number of unique cities:");

        numberCities.setEnabled(false);

        jLabel5.setText("Number of unique states:");

        numberStates.setEnabled(false);

        jbRunSystem.setText("Insert the records in the database");
        jbRunSystem.setEnabled(false);
        jbRunSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRunSystemActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(selectedFilesJList);

        javax.swing.GroupLayout jpLoadDataLayout = new javax.swing.GroupLayout(jpLoadData);
        jpLoadData.setLayout(jpLoadDataLayout);
        jpLoadDataLayout.setHorizontalGroup(
            jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoadDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLoadDataLayout.createSequentialGroup()
                        .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbInputFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(8, 8, 8)
                        .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalRegisters, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(numberCities)
                            .addComponent(numberStates)))
                    .addComponent(jbRunSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jpLoadDataLayout.setVerticalGroup(
            jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoadDataLayout.createSequentialGroup()
                .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLoadDataLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jbInputFileButton)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpLoadDataLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(totalRegisters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(numberCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(numberStates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRunSystem)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jtfNumberThree.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtfNumberThree.setText("C");

        jtfNumberOne.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtfNumberOne.setText("A");

        jpFindIsolationIndex.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Find Isolation Index")));

        jLabel14.setText("Highest Isolation:");

        highestIsolationIndex.setEnabled(false);

        jLabel15.setText("Lowest Isolation:");

        lowestIsolationIndex.setEnabled(false);

        jbFindIsolationIndex.setText("Search");
        jbFindIsolationIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFindIsolationIndexActionPerformed(evt);
            }
        });

        jLabel11.setText("Where:");

        jcbWhereToFind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brazil", "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA)", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));

        javax.swing.GroupLayout jpFindIsolationIndexLayout = new javax.swing.GroupLayout(jpFindIsolationIndex);
        jpFindIsolationIndex.setLayout(jpFindIsolationIndexLayout);
        jpFindIsolationIndexLayout.setHorizontalGroup(
            jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFindIsolationIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(highestIsolationIndex)
                    .addComponent(lowestIsolationIndex)
                    .addGroup(jpFindIsolationIndexLayout.createSequentialGroup()
                        .addGroup(jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jcbWhereToFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFindIsolationIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );
        jpFindIsolationIndexLayout.setVerticalGroup(
            jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFindIsolationIndexLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpFindIsolationIndexLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbWhereToFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jbFindIsolationIndex))
                    .addGroup(jpFindIsolationIndexLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(highestIsolationIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lowestIsolationIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jtfNumberTwo1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtfNumberTwo1.setText("B");

        jpXMLTransformer.setBorder(javax.swing.BorderFactory.createTitledBorder("XML Transformer"));

        jLabel16.setText("File output name:");

        jbExport.setText("Export to XML");
        jbExport.setActionCommand("");
        jbExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpXMLTransformerLayout = new javax.swing.GroupLayout(jpXMLTransformer);
        jpXMLTransformer.setLayout(jpXMLTransformerLayout);
        jpXMLTransformerLayout.setHorizontalGroup(
            jpXMLTransformerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpXMLTransformerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpXMLTransformerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbExport, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpXMLTransformerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addComponent(xmlOutputFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpXMLTransformerLayout.setVerticalGroup(
            jpXMLTransformerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpXMLTransformerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xmlOutputFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbExport)
                .addContainerGap())
        );

        jbExit.setText("Exit");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        jtfNumberFour.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtfNumberFour.setText("D");

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMainLayout.createSequentialGroup()
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbExit))
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfNumberOne)
                            .addComponent(jtfNumberThree))
                        .addGap(11, 11, 11)
                        .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMainLayout.createSequentialGroup()
                                .addComponent(jpFindIsolationIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfNumberFour))
                            .addGroup(jpMainLayout.createSequentialGroup()
                                .addComponent(jpDatabaseConnection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfNumberTwo1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpLoadData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpXMLTransformer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(8, 8, 8))
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfNumberOne)
                    .addComponent(jpLoadData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfNumberTwo1)
                    .addComponent(jpDatabaseConnection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpFindIsolationIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfNumberThree)
                    .addComponent(jtfNumberFour)
                    .addComponent(jpXMLTransformer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jbExit)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        int r = JOptionPane.showConfirmDialog(this, "Do you really want to exit?", "Exit", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbExitActionPerformed

    /**
     * IMPLEMENTA A AÇÃO DO BOTÃO "EXPORT TO XML"
     */
    private void jbExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExportActionPerformed

        final String XML_FILE_NAME = xmlOutputFileName.getText(); // Essa variável contém o nome do arquivo ao qual deve ser exportado o XML

        // Siga aqui seu código

    }//GEN-LAST:event_jbExportActionPerformed

    /**
     * IMPLEMENTA A AÇÃO DO BOTÃO "RUN SYSTEM DATABASE LOAD"
     */
    private void jbRunSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRunSystemActionPerformed
        if (dbName.getText().isEmpty() ||
            port.getText().isEmpty() ||
            hostName.getText().isEmpty() ||
            username.getText().isEmpty() ||
            enableTransactions.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please, first load the XML config", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (records == null || records.isEmpty()) {
           JOptionPane.showMessageDialog(this, "No records loaded from CSV to insert.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        int portValue = Integer.parseInt(port.getText());
        char[] passwordChars = password.getPassword();
        String passwordValue = new String(passwordChars);
        
        DBManager db = new DBManager(
            hostName.getText(),
            portValue,  
            dbName.getText(),
            username.getText(),
            passwordValue
        );
        
        boolean enableTx = enableTransactions.getText().equalsIgnoreCase("yes");
        
        try{
            db.insertAll(records, enableTx);
           JOptionPane.showMessageDialog(this, "All records inserted into database successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error during execution: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbRunSystemActionPerformed

    /**
     * MÉTODO IMPLEMENTADO PARA VOCÊ
     * ESSE MÉTODO IMPLEMENTA A AÇÃO DO BOTÃO "SELECT..."
     */
// ======================================ATIVIDADE 4 AQUI =================================================================================================================================================
    private void jbInputFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputFileButtonActionPerformed

        try {
            fileChooser.setMultiSelectionEnabled(true);
            int result = fileChooser.showOpenDialog(this);
            
            if (result == JFileChooser.CANCEL_OPTION) {
                return;
            }
            
            selectedFiles = fileChooser.getSelectedFiles();
            DefaultListModel<String> model = new DefaultListModel<>();
            
            for (File file : selectedFiles) {
                model.addElement(file.getName());
            }
            
            selectedFilesJList.setModel(model);
            
            records = IsolationCSVImporter.load(selectedFiles);
            
            // esta variável armazenará os estados de modo que cada estado armazena uma lista de cidades cujos nomes não se repetem
            Map<String, Set<String>> data = new HashMap();
            
            for (IsolationRecord r : records) { 
                data.putIfAbsent(r.state(), new HashSet<>());
                data.get(r.state()).add(r.city());
            }
            
            int numeberState = data.size();
            int numeberCity = 0;
            for(Set<String> city : data.values()){
                numeberCity += city.size();
            }
            
            
            // as variáveis _numberOfCities e _numberStates devem receber o número total de cidades e o número total de estados
            // utilize uma estratégia para obter estes dados a partir do mapa "data" declarado logo acima
          
            int _numberOfCities = numeberCity; 
            int _numberStates = numeberState;
            
            totalRegisters.setText(String.valueOf(records.size()));
            numberCities.setText(String.valueOf(_numberOfCities));
            numberStates.setText(String.valueOf(_numberStates));
            
            // habilita o botão de execução da operação de inserção dos dados no banco de dados.
            jbRunSystem.setEnabled(true);
        } catch (InterruptedException ex) {
            System.getLogger(MainFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_jbInputFileButtonActionPerformed

    // ===================================================ATIVIDADE 3 AQUI=======================================================================================================================================
    /**
     * IMPLEMENTA A AÇÃO DO BOTÃO "LOAD XML CONF"   
     */
    private void jbLoadXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoadXMLActionPerformed
        final String CONFIG_FILE_NAME = "config.xml";

        // Insira aqui seu código para implementar a ação do botão "Load XML Conf".
        // Esse código deve extrair dados do arquivo indicado na contante acima utilizando XPath
        
        var xml = XMLHandler.readXmlFile(CONFIG_FILE_NAME);
        
        String _username           = XMLHandler.getXMLValue(xml, "/config/database/@username");
        String _password           = XMLHandler.getXMLValue(xml, "/config/database/@password");
        String _hostName           = XMLHandler.getXMLValue(xml, "/config/database/@host-name");
        String _port               = XMLHandler.getXMLValue(xml, "/config/database/@port");
        String _dbName             = XMLHandler.getXMLValue(xml, "/config/database/@db-name");
        String _enableTransactions = XMLHandler.getXMLValue(xml, "/config/database/@enable-transactions");
        
        
        username.setText(_username);
        password.setText(_password);
        hostName.setText(_hostName);
        port.setText(_port);
        dbName.setText(_dbName);
        enableTransactions.setText(_enableTransactions);
    }//GEN-LAST:event_jbLoadXMLActionPerformed

//================================================ATIVIDADE 5 AQUI ==============================================================================================================================================
    private void jbFindIsolationIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFindIsolationIndexActionPerformed

        final String WHERE_TO_FIND = jcbWhereToFind.getSelectedItem().toString(); // Essa variável contém o nome e a sigla do estado selecionado
          new Thread(() -> {
        try {

            DBManager db = new DBManager(
                    hostName.getText(),
                    Integer.parseInt(port.getText()),
                    dbName.getText(),
                    username.getText(),
                    new String(password.getPassword())
            );

            ExecutorService executor = Executors.newFixedThreadPool(2);

            Future<IsolationRecord> highestFuture =
                    executor.submit(() ->
                            db.findTheHighest(WHERE_TO_FIND));

            Future<IsolationRecord> lowestFuture =
                    executor.submit(() ->
                            db.findTheLowest(WHERE_TO_FIND));

            IsolationRecord highest = highestFuture.get();
            IsolationRecord lowest = lowestFuture.get();

            executor.shutdown();

            SwingUtilities.invokeLater(() -> {

                if (highest != null) {
                    highestIsolationIndex.setText(
                        highest.city()
                        + " (" + highest.date() + ") -> "
                        + String.format("%.2f", highest.index()) + "%"
                    );
                }

                if (lowest != null) {
                    lowestIsolationIndex.setText(
                        lowest.city()
                        + " (" + lowest.date() + ") -> "
                        + String.format("%.2f", lowest.index()) + "%"
                    );
                }
            });

        } catch (Exception e) {
            e.printStackTrace();
        }
    }).start();
    }//GEN-LAST:event_jbFindIsolationIndexActionPerformed

    private void hostNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostNameActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dbName;
    private javax.swing.JTextField enableTransactions;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField highestIsolationIndex;
    private javax.swing.JTextField hostName;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbExport;
    private javax.swing.JButton jbFindIsolationIndex;
    private javax.swing.JButton jbInputFileButton;
    private javax.swing.JButton jbLoadXML;
    private javax.swing.JButton jbRunSystem;
    private javax.swing.JComboBox<String> jcbWhereToFind;
    private javax.swing.JPanel jpDatabaseConnection;
    private javax.swing.JPanel jpFindIsolationIndex;
    private javax.swing.JPanel jpLoadData;
    private javax.swing.JPanel jpMain;
    private javax.swing.JPanel jpXMLTransformer;
    private javax.swing.JLabel jtfNumberFour;
    private javax.swing.JLabel jtfNumberOne;
    private javax.swing.JLabel jtfNumberThree;
    private javax.swing.JLabel jtfNumberTwo1;
    private javax.swing.JTextField lowestIsolationIndex;
    private javax.swing.JTextField numberCities;
    private javax.swing.JTextField numberStates;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField port;
    private javax.swing.JList<String> selectedFilesJList;
    private javax.swing.JTextField totalRegisters;
    private javax.swing.JTextField username;
    private javax.swing.JTextField xmlOutputFileName;
    // End of variables declaration//GEN-END:variables

    private File[] selectedFiles;
    private List<IsolationRecord> records = new ArrayList();
    
}
